variable "ENVIRONMENT" {
    default = "veerum"
}

variable "REGION" {
    default = "us-west-2"
}

variable "PROFILE" {
    default = "default"
}

variable "REMOTE_STATE_BUCKET" {
    default = "TerraForm"
}

variable "REMOTE_STATE_KEY" {
    default = "Veerum"
}

variable "KEY_NAME" {
    default = "VeerumKey"
}

variable "KEY_PUBLIC" {
    default = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDvEzpg/U7ucCI+Mi/LfPY4vztyoEZS9iQU+sWQj7Ifva1ytFaf+P1XggPS1eLgEc4jPPKm/bb9oiDiMjLSsKWh+ytUk9h09pfLGnnwtqGwLYOZ2qIAKtlsRnEIQ7T0M95ZhtSkjnh/Sqw255QmHe55SOf9ACIUgEGtcjUOomc+KA5jalIPxWBbu8xBQhOlg3HFJG7yPFI109uHcPZMNztna/3X0crzucQRQKGXxu6hitoiRvnzSZnWbzZ6jM9NZlSJJe6oKD7PylGZMXkAJTl8A+ZTxzcy9yo9NIIjX/31DJwkVfG7LeCvz/Ya9ev+EMoQp+sNJo/6iI6iOfHnJPAz"
}

#variable "KEY_PUBLIC_PATH" { } # Replaced by in-line public key variable above, as recommended by Terraform best practices document.

#variable "KEY_PRIVATE_PATH" { } # This variable isn't used in this Terraform configuration.

variable "USERS_LOCAL_CIDR" {
    default = "0.0.0.0/0"
}

variable "VPC_CIDR" {
    default = "10.0.0.0/16"
}

variable "PUBLIC_SUBNET_A_CIDR" {
    default = "10.0.1.0/24"
}

variable "PRIVATE_SUBNET_A_CIDR" {
    default = "10.0.4.0/24"
}

variable "PUBLIC_SUBNET_B_CIDR" {
    default = "10.0.2.0/24"
}

variable "PRIVATE_SUBNET_B_CIDR" {
    default = "10.0.5.0/24"
}

variable "PUBLIC_SUBNET_C_CIDR" {
    default = "10.0.3.0/24"
}

variable "PRIVATE_SUBNET_C_CIDR" {
    default = "10.0.6.0/24"
}

variable "KUBERNETES_CLUSTER_NAME" {
    default = "VeerumKluster"
}

#variable "KUBERNETES_CLUSTER_KEY" { } # This is autogenerated and tagged by EKS, and should be set appropriately.

variable "KUBERNETES_CLUSTER_VALUE" {
    default = "owned"
}

variable "KUBERNETES_ELB_INTERNAL_KEY" {
    default = "elb-int-key"
}

variable "KUBERNETES_ELB_INTERNAL_VALUE" {
    default = "elb-int-val"
}

variable "KUBERNETES_ELB_KEY" {
    default = "elb-key"
}

variable "KUBERNETES_ELB_VALUE" {
    default = "elb-value"
}
