apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: node-hello
spec:
  selector:
    matchLabels:
      app: node-hello
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: node-hello
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: eatatjoes/docker-demo:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: node-hello
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: node-hello
    tier: frontend
